In [0]:
#Name: Deepika Mahajan
#Neptun Code: T1VISF
#Assignment 1 : Count-Min Sketch Implimentation

In [65]:
!pip install mmh3
import numpy as np
import pandas as pd 
import random
import mmh3

In [67]:
#To enter number of Hash Fuctions
num_hashFunc = int (input("Enter: Number of Hash Function:" ))

#To enter Hash Range
num_hashRange = int (input("Enter: Number of Hash Range:" ))

#To enter Stream Size
StreamSize = int(input("Enter: Number of Stream Size (Sample):" ))

Enter: Number of Hash Function:10
Enter: Number of Hash Range:9
Enter: Number of Stream Size (Sample):1000


In [68]:
#Problem: Stream Data Frequency 
Inputletter = ['A', 'B', 'C', 'D', 'E']
print(Inputletter)

['A', 'B', 'C', 'D', 'E']


In [69]:
#RandomFunction: For Generating Random Numbers
Streamdata = np.random.choice(Inputletter, StreamSize)
print(Streamdata)

['B' 'D' 'B' 'C' 'A' 'E' 'C' 'B' 'C' 'D' 'B' 'D' 'D' 'D' 'B' 'B' 'D' 'A'
 'A' 'C' 'D' 'D' 'B' 'D' 'A' 'C' 'E' 'C' 'C' 'B' 'C' 'C' 'A' 'A' 'D' 'C'
 'A' 'A' 'E' 'C' 'D' 'E' 'C' 'B' 'C' 'D' 'B' 'B' 'A' 'B' 'D' 'B' 'A' 'A'
 'D' 'C' 'E' 'D' 'D' 'A' 'C' 'E' 'D' 'D' 'E' 'B' 'B' 'E' 'A' 'A' 'D' 'D'
 'D' 'B' 'C' 'E' 'B' 'C' 'C' 'A' 'D' 'D' 'A' 'E' 'E' 'C' 'D' 'C' 'E' 'C'
 'E' 'B' 'E' 'E' 'C' 'B' 'E' 'D' 'D' 'C' 'A' 'C' 'B' 'D' 'D' 'D' 'D' 'A'
 'A' 'E' 'A' 'D' 'A' 'D' 'D' 'D' 'D' 'D' 'B' 'A' 'A' 'A' 'C' 'A' 'A' 'B'
 'A' 'A' 'E' 'E' 'A' 'B' 'C' 'B' 'B' 'B' 'C' 'E' 'D' 'C' 'C' 'E' 'B' 'B'
 'C' 'B' 'A' 'A' 'A' 'E' 'A' 'E' 'A' 'B' 'A' 'B' 'C' 'A' 'A' 'D' 'A' 'B'
 'C' 'E' 'A' 'D' 'A' 'E' 'A' 'D' 'C' 'B' 'C' 'E' 'E' 'B' 'E' 'C' 'A' 'C'
 'E' 'C' 'E' 'C' 'C' 'C' 'E' 'C' 'C' 'E' 'A' 'C' 'E' 'E' 'A' 'E' 'A' 'E'
 'B' 'E' 'D' 'E' 'E' 'E' 'D' 'B' 'A' 'B' 'D' 'C' 'D' 'D' 'D' 'D' 'C' 'C'
 'D' 'C' 'E' 'B' 'A' 'A' 'A' 'A' 'B' 'C' 'C' 'B' 'C' 'D' 'E' 'B' 'B' 'D'
 'E' 'D' 'D' 'D' 'A' 'B' 'B' 'A' 'E' 'D' 'B' 'E' 'C

In [70]:
#CountMinSketch
countMinSketch = np.zeros((num_hashFunc,num_hashRange))
print(countMinSketch)


[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [71]:
for i in Streamdata:
  for j in range(num_hashFunc):
    X = mmh3.hash(i, j) % num_hashRange
    countMinSketch[j,X] += 1
print(countMinSketch)

[[182. 239.   0.   0.   0. 199. 183. 197.   0.]
 [  0. 197. 182.   0.   0. 438.   0. 183.   0.]
 [  0. 562. 239.   0.   0. 199.   0.   0.   0.]
 [  0. 199.   0.   0.   0. 239. 182. 380.   0.]
 [  0. 199.   0.   0. 239.   0. 182.   0. 380.]
 [197.   0. 199. 182.   0. 183. 239.   0.   0.]
 [  0.   0. 197. 199.   0. 239. 183.   0. 182.]
 [  0. 182.   0. 199. 197.   0. 239.   0. 183.]
 [436.   0.   0. 182.   0.   0.   0. 199. 183.]
 [  0.   0.   0. 199.   0. 239.   0. 379. 183.]]


In [75]:
#Count of Letter Frequency
Freq_counts = dict()
loc = np.zeros((len(Inputletter), num_hashFunc))
for i in Inputletter:
  for j in range(num_hashFunc):
    X = mmh3.hash(i,j) % num_hashRange
    loc[Inputletter.index(i),j] = countMinSketch[j, X]
  Freq_counts[i] = np.amin(loc[Inputletter.index(i)])
print(Freq_counts)

{'A': 239.0, 'B': 197.0, 'C': 183.0, 'D': 199.0, 'E': 182.0}
